#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kwidgetsaddons
Version  : 5.49.0
Release  : 2
URL      : https://download.kde.org/stable/frameworks/5.49/kwidgetsaddons-5.49.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.49/kwidgetsaddons-5.49.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.49/kwidgetsaddons-5.49.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 ICU LGPL-2.1
Requires: kwidgetsaddons-lib
Requires: kwidgetsaddons-license
Requires: kwidgetsaddons-data
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
# KWidgetsAddons
Large set of desktop widgets
## Introduction
This repository contains add-on widgets and classes for applications
that use the Qt Widgets module. If you are porting applications from
KDE Platform 4 "kdeui" library, you will find many of its classes here.

%package data
Summary: data components for the kwidgetsaddons package.
Group: Data

%description data
data components for the kwidgetsaddons package.


%package dev
Summary: dev components for the kwidgetsaddons package.
Group: Development
Requires: kwidgetsaddons-lib
Requires: kwidgetsaddons-data
Provides: kwidgetsaddons-devel

%description dev
dev components for the kwidgetsaddons package.


%package lib
Summary: lib components for the kwidgetsaddons package.
Group: Libraries
Requires: kwidgetsaddons-data
Requires: kwidgetsaddons-license

%description lib
lib components for the kwidgetsaddons package.


%package license
Summary: license components for the kwidgetsaddons package.
Group: Default

%description license
license components for the kwidgetsaddons package.


%prep
%setup -q -n kwidgetsaddons-5.49.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534092061
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1534092061
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kwidgetsaddons
cp COPYING %{buildroot}/usr/share/doc/kwidgetsaddons/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/kwidgetsaddons/COPYING.LIB
cp LICENSE.Unicode %{buildroot}/usr/share/doc/kwidgetsaddons/LICENSE.Unicode
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kf5/kcharselect/kcharselect-data
/usr/share/locale/af/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ar/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/as/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ast/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/be/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/be@latin/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/bg/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/bn/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/bn_IN/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/br/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/bs/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ca/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/crh/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/cs/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/csb/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/cy/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/da/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/de/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/el/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/en/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/eo/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/es/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/et/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/eu/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/fa/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/fi/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/fr/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/fy/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ga/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/gl/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/gu/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ha/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/he/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hi/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hne/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hr/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hsb/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hu/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/hy/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ia/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/id/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/is/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/it/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ja/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ka/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/kk/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/km/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/kn/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ko/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ku/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/lb/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/lt/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/lv/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/mai/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/mk/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ml/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/mr/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ms/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/nb/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/nds/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ne/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/nl/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/nn/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/oc/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/or/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/pa/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/pl/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ps/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/pt/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ro/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ru/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/se/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/si/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sk/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sl/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sq/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sr/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/sv/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ta/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/te/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/tg/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/th/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/tr/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/tt/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/ug/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/uk/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/uz/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/vi/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/wa/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/xh/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/zh_HK/LC_MESSAGES/kwidgetsaddons5_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/kwidgetsaddons5_qt.qm

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KWidgetsAddons/KAcceleratorManager
/usr/include/KF5/KWidgetsAddons/KActionMenu
/usr/include/KF5/KWidgetsAddons/KActionSelector
/usr/include/KF5/KWidgetsAddons/KAnimatedButton
/usr/include/KF5/KWidgetsAddons/KAssistantDialog
/usr/include/KF5/KWidgetsAddons/KCapacityBar
/usr/include/KF5/KWidgetsAddons/KCharSelect
/usr/include/KF5/KWidgetsAddons/KCollapsibleGroupBox
/usr/include/KF5/KWidgetsAddons/KColorButton
/usr/include/KF5/KWidgetsAddons/KColorCombo
/usr/include/KF5/KWidgetsAddons/KColumnResizer
/usr/include/KF5/KWidgetsAddons/KCursor
/usr/include/KF5/KWidgetsAddons/KDateComboBox
/usr/include/KF5/KWidgetsAddons/KDatePicker
/usr/include/KF5/KWidgetsAddons/KDateTimeEdit
/usr/include/KF5/KWidgetsAddons/KDragWidgetDecorator
/usr/include/KF5/KWidgetsAddons/KDualAction
/usr/include/KF5/KWidgetsAddons/KEditListWidget
/usr/include/KF5/KWidgetsAddons/KFontAction
/usr/include/KF5/KWidgetsAddons/KFontChooser
/usr/include/KF5/KWidgetsAddons/KFontRequester
/usr/include/KF5/KWidgetsAddons/KFontSizeAction
/usr/include/KF5/KWidgetsAddons/KGradientSelector
/usr/include/KF5/KWidgetsAddons/KGuiItem
/usr/include/KF5/KWidgetsAddons/KLed
/usr/include/KF5/KWidgetsAddons/KMessageBox
/usr/include/KF5/KWidgetsAddons/KMessageBoxDontAskAgainInterface
/usr/include/KF5/KWidgetsAddons/KMessageBoxNotifyInterface
/usr/include/KF5/KWidgetsAddons/KMessageWidget
/usr/include/KF5/KWidgetsAddons/KMimeTypeChooser
/usr/include/KF5/KWidgetsAddons/KMimeTypeChooserDialog
/usr/include/KF5/KWidgetsAddons/KMimeTypeEditor
/usr/include/KF5/KWidgetsAddons/KMultiTabBar
/usr/include/KF5/KWidgetsAddons/KMultiTabBarButton
/usr/include/KF5/KWidgetsAddons/KMultiTabBarTab
/usr/include/KF5/KWidgetsAddons/KNewPasswordDialog
/usr/include/KF5/KWidgetsAddons/KNewPasswordWidget
/usr/include/KF5/KWidgetsAddons/KPageDialog
/usr/include/KF5/KWidgetsAddons/KPageModel
/usr/include/KF5/KWidgetsAddons/KPageView
/usr/include/KF5/KWidgetsAddons/KPageWidget
/usr/include/KF5/KWidgetsAddons/KPageWidgetItem
/usr/include/KF5/KWidgetsAddons/KPageWidgetModel
/usr/include/KF5/KWidgetsAddons/KPasswordDialog
/usr/include/KF5/KWidgetsAddons/KPasswordLineEdit
/usr/include/KF5/KWidgetsAddons/KPixmapRegionSelectorDialog
/usr/include/KF5/KWidgetsAddons/KPixmapRegionSelectorWidget
/usr/include/KF5/KWidgetsAddons/KPixmapSequence
/usr/include/KF5/KWidgetsAddons/KPixmapSequenceOverlayPainter
/usr/include/KF5/KWidgetsAddons/KPixmapSequenceWidget
/usr/include/KF5/KWidgetsAddons/KPopupFrame
/usr/include/KF5/KWidgetsAddons/KRatingPainter
/usr/include/KF5/KWidgetsAddons/KRatingWidget
/usr/include/KF5/KWidgetsAddons/KRuler
/usr/include/KF5/KWidgetsAddons/KSelectAction
/usr/include/KF5/KWidgetsAddons/KSelector
/usr/include/KF5/KWidgetsAddons/KSeparator
/usr/include/KF5/KWidgetsAddons/KSplitterCollapserButton
/usr/include/KF5/KWidgetsAddons/KSqueezedTextLabel
/usr/include/KF5/KWidgetsAddons/KStandardGuiItem
/usr/include/KF5/KWidgetsAddons/KStyleExtensions
/usr/include/KF5/KWidgetsAddons/KTimeComboBox
/usr/include/KF5/KWidgetsAddons/KTitleWidget
/usr/include/KF5/KWidgetsAddons/KToggleAction
/usr/include/KF5/KWidgetsAddons/KToggleFullScreenAction
/usr/include/KF5/KWidgetsAddons/KToolBarLabelAction
/usr/include/KF5/KWidgetsAddons/KToolBarPopupAction
/usr/include/KF5/KWidgetsAddons/KToolBarSpacerAction
/usr/include/KF5/KWidgetsAddons/KToolTipWidget
/usr/include/KF5/KWidgetsAddons/KUrlLabel
/usr/include/KF5/KWidgetsAddons/KViewStateMaintainerBase
/usr/include/KF5/KWidgetsAddons/KViewStateSerializer
/usr/include/KF5/KWidgetsAddons/KXYSelector
/usr/include/KF5/KWidgetsAddons/LineEditUrlDropEventFilter
/usr/include/KF5/KWidgetsAddons/kacceleratormanager.h
/usr/include/KF5/KWidgetsAddons/kactionmenu.h
/usr/include/KF5/KWidgetsAddons/kactionselector.h
/usr/include/KF5/KWidgetsAddons/kanimatedbutton.h
/usr/include/KF5/KWidgetsAddons/kassistantdialog.h
/usr/include/KF5/KWidgetsAddons/kcapacitybar.h
/usr/include/KF5/KWidgetsAddons/kcharselect.h
/usr/include/KF5/KWidgetsAddons/kcollapsiblegroupbox.h
/usr/include/KF5/KWidgetsAddons/kcolorbutton.h
/usr/include/KF5/KWidgetsAddons/kcolorcombo.h
/usr/include/KF5/KWidgetsAddons/kcolumnresizer.h
/usr/include/KF5/KWidgetsAddons/kcursor.h
/usr/include/KF5/KWidgetsAddons/kdatecombobox.h
/usr/include/KF5/KWidgetsAddons/kdatepicker.h
/usr/include/KF5/KWidgetsAddons/kdatetimeedit.h
/usr/include/KF5/KWidgetsAddons/kdragwidgetdecorator.h
/usr/include/KF5/KWidgetsAddons/kdualaction.h
/usr/include/KF5/KWidgetsAddons/keditlistwidget.h
/usr/include/KF5/KWidgetsAddons/kfontaction.h
/usr/include/KF5/KWidgetsAddons/kfontchooser.h
/usr/include/KF5/KWidgetsAddons/kfontrequester.h
/usr/include/KF5/KWidgetsAddons/kfontsizeaction.h
/usr/include/KF5/KWidgetsAddons/kguiitem.h
/usr/include/KF5/KWidgetsAddons/kled.h
/usr/include/KF5/KWidgetsAddons/kmessagebox.h
/usr/include/KF5/KWidgetsAddons/kmessageboxdontaskagaininterface.h
/usr/include/KF5/KWidgetsAddons/kmessageboxnotifyinterface.h
/usr/include/KF5/KWidgetsAddons/kmessagewidget.h
/usr/include/KF5/KWidgetsAddons/kmimetypechooser.h
/usr/include/KF5/KWidgetsAddons/kmimetypeeditor.h
/usr/include/KF5/KWidgetsAddons/kmultitabbar.h
/usr/include/KF5/KWidgetsAddons/knewpassworddialog.h
/usr/include/KF5/KWidgetsAddons/knewpasswordwidget.h
/usr/include/KF5/KWidgetsAddons/kpagedialog.h
/usr/include/KF5/KWidgetsAddons/kpagemodel.h
/usr/include/KF5/KWidgetsAddons/kpageview.h
/usr/include/KF5/KWidgetsAddons/kpagewidget.h
/usr/include/KF5/KWidgetsAddons/kpagewidgetmodel.h
/usr/include/KF5/KWidgetsAddons/kpassworddialog.h
/usr/include/KF5/KWidgetsAddons/kpasswordlineedit.h
/usr/include/KF5/KWidgetsAddons/kpixmapregionselectordialog.h
/usr/include/KF5/KWidgetsAddons/kpixmapregionselectorwidget.h
/usr/include/KF5/KWidgetsAddons/kpixmapsequence.h
/usr/include/KF5/KWidgetsAddons/kpixmapsequenceoverlaypainter.h
/usr/include/KF5/KWidgetsAddons/kpixmapsequencewidget.h
/usr/include/KF5/KWidgetsAddons/kpopupframe.h
/usr/include/KF5/KWidgetsAddons/kratingpainter.h
/usr/include/KF5/KWidgetsAddons/kratingwidget.h
/usr/include/KF5/KWidgetsAddons/kruler.h
/usr/include/KF5/KWidgetsAddons/kselectaction.h
/usr/include/KF5/KWidgetsAddons/kselector.h
/usr/include/KF5/KWidgetsAddons/kseparator.h
/usr/include/KF5/KWidgetsAddons/ksplittercollapserbutton.h
/usr/include/KF5/KWidgetsAddons/ksqueezedtextlabel.h
/usr/include/KF5/KWidgetsAddons/kstandardguiitem.h
/usr/include/KF5/KWidgetsAddons/kstyleextensions.h
/usr/include/KF5/KWidgetsAddons/ktimecombobox.h
/usr/include/KF5/KWidgetsAddons/ktitlewidget.h
/usr/include/KF5/KWidgetsAddons/ktoggleaction.h
/usr/include/KF5/KWidgetsAddons/ktogglefullscreenaction.h
/usr/include/KF5/KWidgetsAddons/ktoolbarlabelaction.h
/usr/include/KF5/KWidgetsAddons/ktoolbarpopupaction.h
/usr/include/KF5/KWidgetsAddons/ktoolbarspaceraction.h
/usr/include/KF5/KWidgetsAddons/ktooltipwidget.h
/usr/include/KF5/KWidgetsAddons/kurllabel.h
/usr/include/KF5/KWidgetsAddons/kviewstatemaintainerbase.h
/usr/include/KF5/KWidgetsAddons/kviewstateserializer.h
/usr/include/KF5/KWidgetsAddons/kwidgetsaddons_export.h
/usr/include/KF5/KWidgetsAddons/kxyselector.h
/usr/include/KF5/KWidgetsAddons/lineediturldropeventfilter.h
/usr/include/KF5/kwidgetsaddons_version.h
/usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfig.cmake
/usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsConfigVersion.cmake
/usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5WidgetsAddons/KF5WidgetsAddonsTargets.cmake
/usr/lib64/libKF5WidgetsAddons.so
/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5WidgetsAddons.so.5
/usr/lib64/libKF5WidgetsAddons.so.5.49.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/kwidgetsaddons/COPYING
/usr/share/doc/kwidgetsaddons/COPYING.LIB
/usr/share/doc/kwidgetsaddons/LICENSE.Unicode
